
export const RETAILERS = [
    "Holland and Barrett",
    "Boots",
    "Sainsbury's",
    "Ocado",
    "Tesco",
    "Waitrose",
    "Asda",
    "Morrisons"
];

export const TRIGGER_PHRASES = [
    "new in",
    "now available",
    "just launched",
    "launching today",
    "just landed",
    "now stocked",
    "on shelves",
    "in stores now",
    "available in store",
    "listed with",
    "range launch",
    "exclusive to",
    "we’re excited to announce",
    "thrilled to share",
    "proud to announce",
    "big news",
    "huge milestone",
    "excited to share that",
    "delighted to announce",
    "now available at",
    "listed in",
    "rolling out to",
    "nationwide rollout",
    "available online at",
    "available in-store and online",
    "coming soon to",
    "landing soon",
    "preparing for launch",
    "next up:",
    "first retail partner",
    "soft launch",
    "shelfie",
    "first grocery listing",
    "retail debut",
    "launching into",
    "hit the shelves",
    "new listing",
    "first listing",
    "stockist",
    "find us at",
    "grab yours",
    "pick up at",
    "look out for",
    "keep an eye out",
    "spotted in",
    "spotted at",
    "live at",
    "live in",
    "buy now",
    "shop now",
    "our new",
    "brand new",
    "available from",
    "find us on the shelves",
    "on the shelf",
    "hitting stores",
    "arriving in",
    "arriving at"
];
